import 'package:flutter_riverpod/flutter_riverpod.dart';

enum AppLanguage { fr, wo }

class LocalizationState {
  final AppLanguage language;

  LocalizationState({this.language = AppLanguage.fr});

  String translate(String key) {
    if (language == AppLanguage.fr) {
      return _fr[key] ?? key;
    } else {
      return _wo[key] ?? _fr[key] ?? key;
    }
  }

  static const Map<String, String> _fr = {
    'honor_score_title': 'Score d\'Honneur',
    'honor_score_status': 'Réputation : Standard',
    'honor_score_excellent': 'Réputation : Excellent ⭐',
    'honor_score_good': 'Réputation : Bon',
    'honor_score_low': 'Réputation : À améliorer',
    'honor_score_welcome': 'Bienvenue sur Tontetic ! Vous commencez avec un Score d\'Honneur de 50. Votre assiduite determinera votre acces aux futurs cercles et marchands Premium. Chaque paiement valide augmente votre score.',
    'coach_signature': 'Tontii (votre Coach Financier) :',
    'coach_bravo_msg': '« Bravo ! Votre assiduité ce mois-ci a maintenu votre score à 50. Continuez ainsi pour atteindre le niveau 60 et débloquer les tontines "Électroménager" ! »',
    'rules_title': 'Règles de Fiabilité ⚖️',
    'rules_content': 'Votre Score d\'Honneur (0-100) est le reflet de votre comportement sur la plateforme. \n\n📈 +5 points : Par cotisation payée à temps.\n⚠️ -20 points : Par retard de paiement.\n🚫 < 30 : Accès restreint aux cercles publiques.\n✨ > 80 : Accès aux Cercles Marchands Premium (Achat immédiat).',
    'coach_greeting': 'Bonjour ! Je suis Tontii (votre Coach Financier) 🧠.\nPosez-moi une question sur vos finances ou nos tontines ! Je suis là pour vous accompagner.',
    'tontii_typing': 'Tontii réfléchit...',
    'ask_question': 'Posez votre question...',
    'my_tontines': 'Mes Tontines',
    'explore': 'Explorer',
    'community': 'Communauté',
    'sim_target_amount': 'Montant cible',
    'sim_monthly_contribution': 'Mensualité',
    'sim_estimated_time': 'Temps estimé',
    'sim_solo_label': 'Économie Solo',
    'sim_tontine_label': 'Effet Tontine',
    'sim_coach_expl': 'Regardez cet avantage ! Seul, vous avancez à votre rythme, mais ensemble, vous accédez à vos rêves beaucoup plus vite.',
    'sim_legal_note': 'Ceci est une illustration technique. Les montants sont dépendants de la diligence des membres.',
    'dir_bi': 'Durée',
    'ki_jel': 'Bénéficiaire',
    'legal_primacy': 'En cas de divergence d\'interprétation, la version française des conditions générales fait foi.',
    'tab_home': 'Accueil',
    'tab_explore': 'Explorer',
    'tab_wallet': 'Portefeuille',
    'tab_merchant': 'Marchands',
    'search_placeholder': 'Chercher projet, membre...',
    'tab_circles': 'Cercles',
    'tab_community': 'Communauté',
    'filter_for_you': 'Pour vous',
    'filter_proximity': 'Proximité',
    'members_count': 'cercles',
    'followers_count': 'abonnés',
    'following': 'Suivi',
    'follow': 'Suivre',
    'request_sent': 'Demande envoyée !',
    'wallet_title': 'Mon Portefeuille',
    'congrats': 'FÉLICITATIONS !',
    'pot_received': 'Vous avez reçu votre pot de ',
    'total_balance': 'Portefeuille Sécurisé',
    'credit_mobile': 'Crédit Mobile',
    'lock_btn': 'Blocage',
    'manage_accounts': 'Gérer mes comptes',
    'graph_soon': 'Données graphiques disponibles prochainement',
    'project_vault': 'Coffre-fort Projet',
    'lock_gains_desc': 'Bloquer des gains pour mon objectif',
    'see_all': 'Voir tout',
    'receipt': 'REÇU',
    'generating_receipt': 'Génération du reçu sécurisé (PDF)...',
    'secure_receipt': '📋 Reçu Sécurisé',
    'receipt_success': 'Votre preuve cryptographique de paiement a été générée avec succès.',
    'open_preview': 'Ouvrir (Aperçu)',
    'deposit': 'Crédit PSP',
    'wealth_analysis': 'Analyse de Patrimoine',
    'organic_growth': 'Croissance organique = Cotisations (0% Intérêts)',
    'project_safe': 'Blocage Volontaire',
    'lock_gains': 'Bloquer des fonds pour mon objectif',
    'zero_commission': '0% Commission Tontetic',
    'zero_commission_desc': 'Nous ne prélevons RIEN sur votre capital. Vos fonds sont sécurisés auprès d\'un partenaire agréé.',
    'transaction_history': 'Historique des opérations',
    'bank_disclaimer': 'Tontetic = prestataire technique. Vos fonds sont détenus par des partenaires financiers agréés, pas par Tontetic.',
    'merchant_tab_title': '🛒 Découverte',
    'like': 'J\'aime',
    'share': 'Partager',
    'save': 'Cotiser',
    'start_saving': 'LANCER MA TONTINE 🚀',
    'hello': 'Bonjour',
    'welcome_back': 'Heureux de vous revoir !',
    'coach_ia': 'Coach IA',
    'sim_my_savings': 'SIMULATION DE TONTINE',
    'launch_offer': 'OFFRE LANCEMENT 🚀',
    'launch_offer_desc': 'Forfait STARTER Offert pendant 3 Mois !',
    'launch_offer_detail': 'Pour les 20 premiers créateurs de cercles Starter et leurs invités : 3 mois offerts.',
    'see_conditions': 'VOIR CONDITIONS & PROFITER',
    'social_proof': '142 personnes ont rejoint Tontetic aujourd\'hui 🚀',
    'profile_title': 'Mon Profil Public',
    'verify_identity': 'Demander ma Certification (Profil de Confiance)',
    'profession': 'Profession',
    'job_label': 'Métier',
    'company_label': 'Entreprise',
    'account_type': 'Type de Compte',
    'bio_label': 'Biographie',
    'speak_about_you': 'Parlez de vous...',
    'privacy_note': 'Votre photo et nom sont toujours publics. Vous contrôlez la visibilité de votre Bio et Métier.',
    'language_label': 'Langue',
    'french': 'Français',
    'wolof': 'Wolof',
    'no_bio': 'Aucune bio pour le moment.',
    'voice_consent_title': 'Autorisation Microphone 🎙️',
    'voice_consent_msg': 'Tontetic souhaite utiliser votre microphone pour transcrire vos messages vocaux. \n\n🔒 Vos audio sont traités uniquement pour la transcription et ne sont pas stockés.',
    'voice_consent_accept': 'AUTORISER & PARLER',
    'voice_consent_decline': 'PLUS TARD',
    'voice_listening': 'Je vous écoute...',
    'voice_understood': 'J\'ai bien reçu votre message vocal. Voici ce que j\'ai compris : ',
    'voice_error_short': 'Message trop court.',
    'voice_error_fail': 'Échec de la transcription.',
    'voice_privacy_note': 'Vos fichiers vocaux sont supprimés immédiatement après leur transcription.',
    'voice_fallback_msg': 'Pardon, je n’ai pas bien saisi votre message. Pourriez-vous répéter un peu plus clairement, ou taper votre demande si vous préférez ? Je suis là pour vous aider !',
    'voice_repeat': 'Répéter',
    'voice_write': 'Écrire',
    'voice_tip': 'Conseil : Essayez de vous rapprocher du micro ou d\'aller dans un endroit plus calme pour que je vous entende mieux ! 🤫',
    'psp_regulatory_banner': 'Fonds sécurisés par un partenaire agréé',
    'bank_disclaimer_short': 'Tontetic = prestataire technique • Fonds détenus par nos partenaires agréés',
    'tech_warning_title': 'Avertissement Technologique',
    'tech_warning_content': 'Tontine Éthique est un prestataire technique. Les cercles affichés ici sont créés par des utilisateurs indépendants. L\'Éditeur ne garantit pas la solvabilité des participants. En continuant, vous reconnaissez que Tontine Éthique n\'est pas un prestataire de services financiers en propre.',
    'tech_banner_text': 'Plateforme technique uniquement • Tontetic ne gère pas les fonds',
    'psp_disclaimer_long': 'Les services de paiement associés aux tontines sont fournis par nos partenaires PSP agréés. Tontine Éthique n’est ni une banque ni un établissement de paiement en propre.',
    'profile_my': 'Mon Profil',
    'profile_of': 'Profil de ',
    'honor_score': 'Score d\'Honneur',
    'followers': 'Abonnés',
    'following_stat': 'Abonnements',
    'tontines_stat': 'Tontines',
    'about_title': 'À propos',
    'invite_to_tontine': 'Inviter à une tontine',
    'mutual_follow_warning': 'Suivez-vous mutuellement pour débloquer les invitations privées.',
    'following_btn': 'Abonné',
    'follow_btn': 'Suivre',
    'what_is_it': 'Qu\'est-ce que c\'est ?',
    'honor_score_desc': 'Le Score d\'Honneur reflète la fiabilité d\'un membre dans ses paiements de cotisations.',
    'rgpd_contact': 'Conformément au RGPD Art. 22, vous pouvez contacter dpo@tontetic.app pour toute question.',
    'cancel': 'Annuler',
    'save_profile_success': 'Profil mis à jour ! ✅',
    'login_required': 'Veuillez vous connecter',
    'photo_update_success': 'Photo de profil mise à jour ! 📸',
    'always_visible': 'Toujours visible',
    'bio_label': 'Bio',
    'job_label': 'Métier',
    'company_label': 'Entreprise',
    'placeholder_bio': 'Parlez de vous...',
    'privacy_legend_title': '🔒 Légende de visibilité',
    'privacy_public': 'Public',
    'privacy_followers': 'Followers',
    'privacy_private': 'Privé',
    'delete_account': 'Supprimer mon compte (RGPD)',
    'confirm_delete_title': 'Supprimer définitivement ?',
    'confirm_delete_content': 'Cette action est irréversible. Toutes vos données seront effacées conformément au RGPD.\n\nÊtes-vous sûr de vouloir continuer ?',
    'upload_error': 'Erreur lors de l\'upload :',
    'merchant_dashboard': 'Dashboard Marchand',
    'access_shop': 'Accéder à ma boutique',
    'manage_shop_desc': 'Gérez vos produits et commandes',
    'become_merchant': 'Devenir Marchand',
    'merchant_creation_desc': 'Créez votre boutique et commencez à vendre',
    'delete_confirm_btn': 'Supprimer',
    'not_set': 'Non renseigné',
    'circle_chat_tooltip': 'Discussion du cercle',
    'vote_order_tooltip': 'Voter pour l\'ordre',
    'share_circle_tooltip': 'Partager ce cercle',
    'more_options': 'Plus d\'options',
    'solarity_title': 'Membres & Solidarité',
    'participants': 'Participants',
    'no_participants': 'Aucun participant pour le moment.',
    'request_approved_title': 'Demande Approuvée !',
    'request_approved_desc': 'L\'administrateur a validé votre demande. Il ne vous reste plus qu\'à signer la charte pour entrer.',
    'sign_and_enter': 'SIGNER ET ENTRER',
    'welcome_member': 'Bienvenue ! Vous êtes maintenant membre.',
    'join_ready_title': 'Prêt à rejoindre ce cercle ?',
    'join_commitment_desc': 'En rejoignant, vous vous engagez à verser @amount par mois.',
    'request_to_join': 'DEMANDER À REJOINDRE',
    'join_requests_title': 'Demandes d\'adhésion',
    'choose_tontine': 'Choisir une tontine',
    'unfollow': 'Ne plus suivre',
    'no_followers': 'Aucun abonné pour le moment',
    'no_following': 'Vous ne suivez personne',
    'calculation_formula': 'Formule de calcul',
    'new_member_start': 'Les nouveaux membres commencent à 4.0/5.',
    'score_excellent': 'Excellent',
    'score_very_good': 'Très bien',
    'score_acceptable': 'Acceptable',
    'score_warning': 'À surveiller',
    'excellent_desc': 'Ce membre a un historique de paiements exemplaire.',
    'very_good_desc': 'Ce membre est généralement fiable.',
    'acceptable_desc': 'Quelques retards occasionnels dans l\'historique.',
    'warning_desc': 'Des retards fréquents ont été constatés.',
    'savings_title': 'Blocage Volontaire',
    'savings_header_title': 'Blocage Volontaire de Fonds',
    'total_locked': 'Total bloqué :',
    'locked_funds_active': 'Fonds Bloqués Actifs',
    'new_locked_savings': 'Nouveau Blocage Volontaire',
    'locked_type': 'Type de blocage',
    'locked_purpose_personal': 'Projet Personnel (Tabaski, rentrée...)',
    'locked_purpose_guarantee': 'Garantie Tontine (1 cotisation)',
    'locked_purpose_contributions': 'Préfinancement Cotisations',
    'project_name_label': 'Nom du projet (ex: Tabaski 2026)',
    'amount_to_lock': 'Montant à bloquer (@currency)',
    'unlock_date_immutable': 'Date de déblocage (IMMUTABLE)',
    'cgu_article_8': 'CGU Article 8 - Épargne Bloquée',
    'view_all': 'Voir tout',
    'cgu_article_4_accept': 'J\'accepte l\'Article 4 CGU - Blocage Volontaire (IRRÉVOCABLE)',
    'block_funds_btn': 'BLOQUER CES FONDS (IRRÉVERSIBLE)',
    'confirm_title': '⚠️ Confirmation Finale',
    'immutable_params_warning': 'ATTENTION : Ces paramètres seront IMMUTABLES',
    'no_mod_after_val': 'Aucune modification possible après validation.\nDéblocage automatique à la date prévue.',
    'savings_success': '✅ Épargne bloquée créée avec succès !',
    'deposit_title': 'Crédit Mobile Money',
    'deposit_amount_q': 'Combien souhaitez-vous créditer ?',
    'choose_payment_method': 'Choisir le moyen de paiement',
    'service_fees': 'Frais de service',
    'operator_fees_notice': '* Frais de l\'opérateur. Tontetic ne prélève aucun pourcentage.',
    'pay_with': 'Payer avec @method',
    'confirm_transaction': 'Confirmer la Transaction',
    'transaction_fee': 'Frais Fixes',
    'total_debited': 'Total Débité',
    'notification_info': 'Vous allez recevoir une notification @method pour confirmer.',
    'connecting_to': 'Connexion à @method...',
    'please_wait': 'Veuillez patienter',
    'payment_initiated': 'Paiement Initié !',
    'return_to_wallet': 'Retour au Portefeuille',
    'ticket_method': 'Méthode',
    'ticket_date': 'Date',
    'amount_label': 'Montant',
    'unlock_label': 'Déblocage',
    'cgu_title': 'CONDITIONS GÉNÉRALES D\'UTILISATION',
    'i_understand': 'J\'ai compris',
    'locked_until': 'Bloqué jusqu\'au',
    'released': 'Libéré',
    'welcome_success': 'Bienvenue ! Vous êtes maintenant membre.',
    'error_label': 'Erreur',
    'join_requests_title': 'Demandes d\'adhésion',
    'request_to_join_title': 'Demande d\'adhésion',
    'join_approval_notice': 'Le créateur du cercle doit approuver votre demande avant que vous puissiez rejoindre.',
    'message_to_creator': 'Message au créateur (optionnel) :',
    'send_request_btn': 'ENVOYER LA DEMANDE',
    'error_must_be_logged': 'Vous devez être connecté pour rejoindre un cercle.',
    'request_sent_success': 'Demande envoyée ! Le créateur sera notifié.',
    'month_suffix': 'mois',
    'solidarity_active': 'Engagement de Solidarité Actif',
    'guarantee_system': 'Système de Garantie',
    'guarantee_desc': 'La garantie protège les membres contre les défauts de paiement.',
    'fonds_locked_escrow': 'Fonds bloqués sur compte séquestre',
    'released_at_end': 'Libérés automatiquement à la fin du cycle',
    'covers_100_default': 'Couvre 100% en cas de défaut',
    'guarantee_usage_info': 'En cas de non-paiement, la garantie est utilisée pour couvrir les autres membres.',
    'membership_code': 'CODE ADHÉSION',
    'share_link_tooltip': 'Partager le lien via WhatsApp, SMS...',
    'invite_member_btn': 'Inviter un membre',
    'no_pending_requests': 'Aucune demande en attente.',
    'request_rejected': 'Demande rejetée',
    'request_approved_success': 'Demande de @name approuvée !',
    'solidarity_executed': 'SOLIDARITÉ EXÉCUTÉE',
    'solidarity_active_member': 'Engagement actif (Solidarité)',
    'leave_circle_tooltip': 'Quitter le cercle',
    'guarantee_used': 'Garantie utilisée',
    'guarantee_ok': 'Garantie OK',
    'share_invite_code': 'Partager le code d\'invitation',
    'no_followers': 'Aucun abonné pour le moment.',
    'no_following': 'Vous ne suivez personne pour le moment.',
    'unfollow': 'Se désabonner',
    'choose_tontine': 'Choisir une tontine',
    'invite_to_tontine': 'Inviter dans une tontine',
    // Payment History Screen
    'payment_history_title': 'Historique des Paiements',
    'filter_all': 'Tout',
    'filter_received': 'Reçu',
    'filter_paid': 'Payé',
    'filter_failed': 'Échoué',
    'no_transactions': 'Aucune transaction',
    'tx_status_success': 'Réussi',
    'tx_status_failed': 'Échoué',
    'tx_details_title': 'Détails de la Transaction',
    'tx_circle': 'Cercle',
    'tx_pot_number': 'Numéro de Pot',
    'tx_type': 'Type',
    'tx_type_received': 'Réception',
    'tx_type_contribution': 'Contribution',
    'tx_amount': 'Montant',
    'tx_date': 'Date',
    'tx_status': 'Statut',
    'tx_reason': 'Raison',
    'close': 'Fermer',
    // Profile Screen extras
    'mutual_friend': 'Ami Mutuel 🤝',
    'score_formula': 'Score = (Paiements réussis / Total) × 5',
    'share_profile_msg': 'Découvre le profil de @name sur Tontetic !',
    'invitation_sent_msg': 'Invitation envoyée à @name !',
    'invite_msg': 'Je t\\'invite à rejoindre ma tontine \"@circle\" !',
    // Circle Details extras
    'share_circle_msg': 'Rejoins ma tontine \"@circle\" sur Tontetic !',
    'invitation_code': 'Code d\\'invitation',
    'direct_link': 'Lien direct',
    'download_app': 'Télécharge l\\'app ici',
    'invitation_subject': 'Invitation Tontine',
    'invitation_ethical': 'Invitation Tontine Éthique',
    'introduce_yourself': 'Présentez-vous brièvement...',
    'request_rejected_msg': 'Demande rejetée',
    'member': 'Membre',
    // Savings extras
    'confirm_amount': 'Montant',
    'confirm_objective': 'Objectif',
    'confirm_unlock': 'Déblocage',
    'default_savings_name': 'Épargne',
    'savings_footer_info': 'Fonds sécurisés auprès d\\'un partenaire agréé.',
    'join_request_subtitle': 'Souhaite rejoindre le cercle',
    'confirm': 'Confirmer',
    'error_missing_fields': 'Veuillez remplir tous les champs',
    'error_accept_cgu': 'Veuillez accepter les CGU',
    'invitation_sent_success': 'Invitation envoyée à @name !',
  };

  static const Map<String, String> _wo = {
    'honor_score_title': 'Score d\'Honneur',
    'honor_score_status': 'Mbooloo : Mi ngi ci diggu',
    'honor_score_excellent': 'Mbooloo : Baax na lool ⭐',
    'honor_score_good': 'Mbooloo : Baax na',
    'honor_score_low': 'Mbooloo : War na yokku',
    'honor_score_welcome': 'Dalal jamm ci Tontetic ! Ngir nu men a am koolute ci sunu diggante, sa Score d\'Honneur 50 la tambalee. Score bi day wone ni nga takku ci sa mbir : fexeel ba sa mbindu (cotisation) yi tegu ci yoon, loolu men na baaxal sa score ba nga men a am solo ak marchand yu am classe. Deet ! Lu sorse (retard) ak sa mbindu day yaq sa reputation ak sa bet ci natt (tontine) yi di new !',
    'coach_signature': 'Tontii (sa Coach Financier) :',
    'coach_bravo_msg': '« Baax na ! Sa assiduité weer wii tax na sa score méngook 50. Wéyal ni ngiy feyee sa mbindu ba nga jot ci niveau 60, loolu dina la may nga jot ci natt "Électroménager" ! »',
    'rules_title': 'Sartu Fiabilité ⚖️',
    'rules_content': 'Sa Score d’Honneur (0-100) moo lay won ni ngay nekke ci plateforme bi. \n\n📈 +5 points : Bo feyee sa mbindu ci waxtu wi.\n⚠️ -20 points : Bo gataxee (retard) ci fey bi.\n🚫 < 30 : Dootoo jot ci yeneen natt yi.\n✨ > 80 : Dinga jot ci Marchands Premium (Jënd léegi jot léegi).',
    'coach_greeting': 'Dalal jàmm ! Man la Tontii (sa Coach Financier) 🧠.\nLaaj ma loo bëgg xam ci sa xaalis walla ci sunu natt yi ! Ma ngi lay topp.',
    'tontii_typing': 'Tontii mi ngi xalaat...',
    'ask_question': 'Laaj ma sa laaj...',
    'my_tontines': 'Sama natt',
    'explore': 'Gëstu',
    'community': 'Mbooloo',
    'legal_wolof_title': 'Sartu Tontetic (Wolof)',
    'role_title': 'Lu Tontetic di def',
    'role_content': 'Tontetic ab jumtukaay la rekk ngir gérée seeni natt. Duñu banque, té duñu téye xaalis. Xaalis bi Stripe wala Wave ñoo koy téye ci seen plateforme yu am kaarange.',
    'honor_score_legal_title': 'Sa Score d’Honneur',
    'honor_score_legal_content': 'Sa Score d’Honneur ci sa feyu mbindu la depand. Boo feye te tegu ci yoon, sa score day yokku. Boo sorsé (retard), sa score day wàññiku.',
    'sim_target_amount': 'Li nga bëgg am',
    'sim_monthly_contribution': 'Li ngay mbindu weer wu ne',
    'sim_estimated_time': 'Dir bi',
    'sim_solo_label': 'Sama bopp',
    'sim_tontine_label': 'Àndandoo',
    'sim_coach_expl': '« Xoolal li ! Boo doon dénc sa xaalis sa bopp rekk (épargne solo), dinga ci tàmbalee lëf ba mu nekk dëgg, waaye mën na la jël ay weer yu bare. Ak Tontetic, yaa ngi bokk natt ak yeneen nit. Loolu day tax nga mën a am li nga bëgg ci weer wu jëkk wi walla wu ñaareel wi. Fi nga doon xaar ba weer wu mujj wi, fii mën nga gawante ba am sa kër, sa oto, walla sa matériel ! »',
    'sim_legal_note': 'Lii ab natt la, feyu mbindu yi ñoo koy dëggal.',
    'dir_bi': 'Dir bi',
    'ki_jel': 'Ki jël',
    'legal_primacy': 'Bu amee lën-lën ci ni ñuy déggé sart yi, version faransé bi mooy dëgg.',
    'tab_home': 'Accueil',
    'tab_explore': 'Gëstu',
    'tab_wallet': 'Xaalis',
    'tab_merchant': 'Jaaykat',
    'search_placeholder': 'Wut ab projet, nit...',
    'tab_circles': 'Natt yi',
    'tab_community': 'Mbooloo',
    'filter_for_you': 'Yaw rekk',
    'filter_proximity': 'Jege',
    'members_count': 'natt',
    'followers_count': 'abonnés',
    'following': 'Wéy',
    'follow': 'Topp',
    'request_sent': 'Yabal nañ ko !',
    'wallet_title': 'Sama Portefeuille',
    'congrats': 'MASHALLAH !',
    'pot_received': 'Jot nga sa pot bu tollu ci ',
    'total_balance': 'Portefeuille Sécurisé',
    'credit_mobile': 'Crédit Mobile',
    'lock_btn': 'Blocage',
    'manage_accounts': 'Gérer mes comptes',
    'graph_soon': 'Données graphiques disponibles prochainement',
    'project_vault': 'Coffre-fort Projet',
    'lock_gains_desc': 'Bloquer des gains pour mon objectif',
    'see_all': 'Gis yëpp',
    'receipt': 'REÇU',
    'generating_receipt': 'Ma ngiy def reçu bi (PDF)...',
    'secure_receipt': '📋 Reçu Sécurisé',
    'receipt_success': 'Sa reçu bi am na léegi.',
    'open_preview': 'Ubbi (Guis)',
    'deposit': 'Crédit PSP',
    'wealth_analysis': 'Xool ni sa xaalis di yokkoo',
    'organic_growth': 'Yokkuté lool : Mbindu yi la (0% Intérêts)',
    'project_safe': 'Blocage Volontaire',
    'lock_gains': 'Téye sa xaalis ngir sa projet',
    'zero_commission': '0% Commission Tontetic',
    'zero_commission_desc': 'Duñu jël lu mat dërëm ci sa xaalis. Sa xaalis mi ngi ci partenaire financier.',
    'transaction_history': 'Jënd ak jaay yi passé',
    'bank_disclaimer': 'Tontetic = prestataire technique. Sa xaalis mi ngi nekk ci partenaire agréé, dula nekk ci Tontetic.',
    'merchant_tab_title': '🛒 Gëstu jaaykat',
    'like': 'Beugg',
    'share': 'Séddo',
    'save': 'Dénc',
    'start_saving': 'TÀMBALEE DÉNC LÉÉGI 🚀',
    'hello': 'Nanga def',
    'welcome_back': 'Beg nañu ci yaw !',
    'coach_ia': 'Tontii Coach',
    'sim_my_savings': 'NATT SIMULATEUR',
    'launch_offer': 'OFFRE LANCEMENT 🚀',
    'launch_offer_desc': '3 Weer yoo feyul dërëm ci Starter !',
    'launch_offer_detail': 'Ngir 20 créateurs yi jëkk ak séen invités : 3 weer offerts.',
    'see_conditions': 'XOOLAL SART YI & PROFITEEL',
    'social_proof': '142 nit bokk nañu ci Tontetic tay 🚀',
    'profile_title': 'Sama Profil',
    'verify_identity': 'Demande sa Certification (Koolute)',
    'profession': 'Liggeey',
    'job_label': 'Léégey',
    'company_label': 'Etablissement',
    'account_type': 'Type de Compte',
    'bio_label': 'Sama mbir',
    'speak_about_you': 'Waxal ci sa bopp...',
    'privacy_note': 'Sa photo ak sa tour ñépp mën nañ ko xool. Yaw yaay gérée sa bio ak sa liggeey.',
    'language_label': 'Lakku',
    'french': 'Faransé',
    'wolof': 'Wolof',
    'no_bio': 'Amagul benn mbir ci boppam.',
    'voice_consent_title': 'Nangu Micro bi 🎙️',
    'voice_consent_msg': 'Tontetic bëgg na jël sa micro ngir bind li ngay wax. \n\n🔒 Sa voice duñ ko téye, dañ koy bind rekk.',
    'voice_consent_accept': 'NANGU NA & WAX',
    'voice_consent_decline': 'BENEEN YOON',
    'voice_listening': 'Ma ngi lay déglu...',
    'voice_understood': 'Jot nañu sa message vocal. Lii lañu ci dégg : ',
    'voice_error_short': 'Message bi gatt na.',
    'voice_error_fail': 'Bind bi sottiwul.',
    'voice_privacy_note': 'Sa voice duñ ko téye, dañ koy bind ba paré fat ko léégi.',
    'voice_fallback_msg': 'Baal ma, dégguma li nga wax bu baax. Mën nga ko waxaat lu leer walla nga mbind ko ci sa téléfon ? Ma ngi lay jàppale !',
    'voice_repeat': 'Waxaat',
    'voice_write': 'Mbind',
    'voice_tip': 'Conseil : Jegeel micro bi walla nga dem fula neex ba ma mën la dégg bu baax ! 🤫',
    'psp_regulatory_banner': 'Xaalis mi ngi ci partenaire financier',
    'bank_disclaimer_short': 'Tontetic = prestataire technique • Sa xaalis mi ngi ci partenaire agréé',
    'tech_warning_title': 'Xébalu Téknik',
    'tech_warning_content': 'Tontine Éthique dafay jappal léen ci wallu téknik rekk. Cercle yii ñu fi wone, nit ñu nekk ci dëkk bi ñooko fital boppam. Tontine Éthique du bank, du établissement de paiement.',
    'tech_banner_text': 'Outil téknik rekk • Tontetic du jël sa xaalis',
    'psp_disclaimer_long': 'Ligueye bi ci wallu xaalis, ay partenaire financiers agréés ñookoy def. Tontine Éthique prestataire technique rekk la.',
    'profile_my': 'Sama Profil',
    'profile_of': 'Profilu ',
    'honor_score': 'Score d\'Honneur',
    'followers': 'Abonnés',
    'following_stat': 'Abonnements',
    'tontines_stat': 'Tontines',
    'about_title': 'Li ma nekk',
    'invite_to_tontine': 'Inviter ci tontine',
    'mutual_follow_warning': 'Toppante léen ngir mëna inviter sen biir.',
    'following_btn': 'Abonné',
    'follow_btn': 'Topp',
    'what_is_it': 'Lan la ?',
    'honor_score_desc': 'Score d\'Honneur bi day wane ni ngay faye sa cotisations.',
    'rgpd_contact': 'Bu amé question ci sa données, bindal dpo@tontetic.app.',
    'cancel': 'Annuler',
    'save_profile_success': 'Profil bi changé na ! ✅',
    'login_required': 'Dafa la faw nga connecter wu',
    'photo_update_success': 'Photo bi changé na ! 📸',
    'always_visible': 'Ñëpp ko mëna guiss',
    'bio_label': 'Bio',
    'job_label': 'Ligueye',
    'company_label': 'Société',
    'placeholder_bio': 'Waxal sa bopp...',
    'privacy_legend_title': '🔒 Ñu mëna guiss',
    'privacy_public': 'Public',
    'privacy_followers': 'Followers',
    'privacy_private': 'Privé',
    'delete_account': 'Supprimer sama compte (RGPD)',
    'confirm_delete_title': 'Supprimer dëgg dëgg ?',
    'confirm_delete_content': 'Lii dula deloussi. Sa données yëpp danañ ko effacer.\n\nNdax paré nga ?',
    'upload_error': 'Njuumte ci upload bi :',
    'merchant_dashboard': 'Dashboard Marchand',
    'access_shop': 'Dem ci sama boutique',
    'manage_shop_desc': 'Gérée sa produits ak commandes',
    'become_merchant': 'Nekk Marchand',
    'merchant_creation_desc': 'Fital sa boutique ba paré jaay',
    'delete_confirm_btn': 'Supprimer',
    'not_set': 'Amagul mbir',
    'circle_chat_tooltip': 'Discussion natt bi',
    'vote_order_tooltip': 'Voter ci kan lay jëkk',
    'share_circle_tooltip': 'Séddo natt bi',
    'more_options': 'Yeneen mbir',
    'solarity_title': 'Membres & Solidarité',
    'participants': 'Participants',
    'no_participants': 'Amagul bénn participant.',
    'request_approved_title': 'Dafa la nangu !',
    'request_approved_desc': 'Admin bi nangu na sa demande. Léegi mbindal sa signature rekk nga duggu.',
    'sign_and_enter': 'MBINDAL & DUGGU',
    'welcome_member': 'Dalal jàmm ! Bokk nga léegi.',
    'join_ready_title': 'Ndax paré nga duggu ?',
    'join_commitment_desc': 'Boo duggu gee, dingay fey @amount weer wu ne.',
    'request_to_join': 'DEMANDE REJOINDRE',
    'join_requests_title': 'Demandes d\'adhésion',
    'choose_tontine': 'Tannal ab natt',
    'unfollow': 'Dootoo topp',
    'no_followers': 'Amul abonnés tay',
    'no_following': 'Toppoo kenn léegi',
    'calculation_formula': 'Nima ñuy xoolé',
    'new_member_start': 'Ñu fess yi 4.0/5 lañuy tàmbalee.',
    'score_excellent': 'Excellent',
    'score_very_good': 'Très bien',
    'score_acceptable': 'Acceptable',
    'score_warning': 'À surveiller',
    'excellent_desc': 'Kii day feyé ci temps.',
    'very_good_desc': 'Kii kuy koolute la.',
    'acceptable_desc': 'Am na yenn retard.',
    'warning_desc': 'Dafay retardé trop.',
    'savings_title': 'Tëj Xaliss',
    'savings_header_title': 'Tëj Xaliss ci PSP bi',
    'total_locked': 'Lii ñu fital :',
    'locked_funds_active': 'Xaliss yu ñu fital léegi',
    'new_locked_savings': 'Tëj Xaliss bu bees',
    'locked_type': 'Luy nax tontine bi',
    'locked_purpose_personal': 'Mbirum bopom (Tabaski, daara...)',
    'locked_purpose_guarantee': 'Garantie Natt (1 feyé)',
    'locked_purpose_contributions': 'Feyé natt bi kanam',
    'project_name_label': 'Turu mbir bi (ex: Tabaski 2026)',
    'amount_to_lock': 'Xaliss bi ñuy tëj (@currency)',
    'unlock_date_immutable': 'Bes bi ñu koy ubbi (Mënuleen ko soppi)',
    'cgu_article_8': 'CGU Article 8 - Tëj Xaliss',
    'view_all': 'Xool yëpp',
    'cgu_article_4_accept': 'Nangu na Article 4 CGU bi (Ubbite bi mënul soppi)',
    'block_funds_btn': 'TËJ XALISS BI (DULOO KO MËN SOPPI)',
    'confirm_title': '⚠️ Déggloo ba paré',
    'immutable_params_warning': 'ATTENTION : Li nga tann mënul soppi',
    'no_mod_after_val': 'Doo mëna soppi dara boo nangu gee.\nXaliss bi dana ubbi ci bes bi nga tann.',
    'savings_success': '✅ Sa xaliss fital nañ ko !',
    'deposit_title': 'Duggal Xaliss Mobile Money',
    'deposit_amount_q': 'Ñata nga bëgga duggal ?',
    'choose_payment_method': 'Tannal nimay feyee',
    'service_fees': 'Frais de service',
    'operator_fees_notice': '* Frais opérateur la. Tontetic du jël dara.',
    'pay_with': 'Feyé ak @method',
    'confirm_transaction': 'Nangu transaction bi',
    'transaction_fee': 'Frais ya',
    'total_debited': 'Lii ñuy jël yëpp',
    'notification_info': 'Dingay jël notification @method ngir nangu.',
    'connecting_to': 'Ñungi dem ci @method...',
    'please_wait': 'Xaaral tuuti',
    'payment_initiated': 'Feyé bi tàmbalee na !',
    'return_to_wallet': 'Dellu ci Portefeuille',
    'ticket_method': 'Péxé bi',
    'ticket_date': 'Bes bi',
    'amount_label': 'Montant',
    'unlock_label': 'Ubbi',
    'cgu_title': 'CONDITIONS GÉNÉRALES D\'UTILISATION',
    'i_understand': 'Dégg na',
    'locked_until': 'Tëj nañ ko ba',
    'released': 'Ubbi na',
    'welcome_success': 'Aksil ak jàmm ! Nékk nga membre léegi.',
    'error_label': 'Njuumte',
    'join_requests_title': 'Ñi bëgga dugg',
    'request_to_join_title': 'Duggal sa demande',
    'join_approval_notice': 'Ki sàkk circle bi mofi mëna nangu sa demande.',
    'message_to_creator': 'Bataaxal (Boo ko bëggée) :',
    'send_request_btn': 'YONNEE DEMANDE BI',
    'error_must_be_logged': 'Fàww nga connecté wu ba paré.',
    'request_sent_success': 'Demande bi dem na ! Kiko sàkk dana ko jël.',
    'month_suffix': 'weer',
    'solidarity_active': 'Garantie Solidarité dax na',
    'guarantee_system': 'Péxé Garantie bi',
    'guarantee_desc': 'Garantie bi day aar membre yi ci ñi dul fey.',
    'fonds_locked_escrow': 'Xaliss bi ñu tëj ci compte séquestre',
    'released_at_end': 'Dana ubbite bu cycle bi jéexée',
    'covers_100_default': 'Day fey 100% bu nit dul fey',
    'guarantee_usage_info': 'Bu ko nit dul feyée, garantie bi lañuy jël fey ko.',
    'membership_code': 'CODE ADHÉSION',
    'share_link_tooltip': 'Partager ko ci WhatsApp, SMS...',
    'invite_member_btn': 'Inviter kénéen',
    'no_pending_requests': 'Dara nekkul fi.',
    'request_rejected': 'Nangu wuñ ko',
    'request_approved_success': 'Demande bu @name nangu nañ ko !',
    'solidarity_executed': 'SOLIDARITÉ BI DEM NA',
    'solidarity_active_member': 'Engagement am na (Solidarité)',
    'leave_circle_tooltip': 'Génn ci tontine bi',
    'guarantee_used': 'Garantie bi jël nañ ko',
    'guarantee_ok': 'Garantie bi baax na',
    'share_invite_code': 'Donner sa code invitation',
    'no_followers': 'Amuloo abonnés léegi.',
    'no_following': 'Topuloo kenn léegi.',
    'unfollow': 'Ba xool kii',
    'choose_tontine': 'Tannal benn tontine',
    'invite_to_tontine': 'Inviter ko ci tontine',
    // Payment History Screen
    'payment_history_title': 'Limu Fey yi',
    'filter_all': 'Yëpp',
    'filter_received': 'Li ñu jël',
    'filter_paid': 'Li ñu fey',
    'filter_failed': 'Li takkuñu wul',
    'no_transactions': 'Amul fey',
    'tx_status_success': 'Dox na',
    'tx_status_failed': 'Doxul',
    'tx_details_title': 'Yeneen Xam-xam',
    'tx_circle': 'Natt bi',
    'tx_pot_number': 'Numéro Pot bi',
    'tx_type': 'Luy nax',
    'tx_type_received': 'Jël',
    'tx_type_contribution': 'Fey',
    'tx_amount': 'Montant',
    'tx_date': 'Bes bi',
    'tx_status': 'Statut',
    'tx_reason': 'Naka waay',
    'close': 'Tëj',
    // Profile Screen extras
    'mutual_friend': 'Xarit bu ñëpp 🤝',
    'score_formula': 'Score = (Paiements réussis / Total) × 5',
    'share_profile_msg': 'Xoolal profilu @name ci Tontetic !',
    'invitation_sent_msg': 'Invitation bi yonnee nañ ko ci @name !',
    'invite_msg': 'Ma bëgg nga bokk sama natt "@circle" !',
    // Circle Details extras
    'share_circle_msg': 'Bokkal sama natt "@circle" ci Tontetic !',
    'invitation_code': 'Code bu duggu',
    'direct_link': 'Lien direct',
    'download_app': 'Télécharger app bi',
    'invitation_subject': 'Invitation Natt',
    'invitation_ethical': 'Invitation Natt Éthique',
    'introduce_yourself': 'Nangal sa bopp...',
    'request_rejected_msg': 'Nangu wuñ sa demande',
    'member': 'Membre',
    // Savings extras
    'confirm_amount': 'Montant',
    'confirm_objective': 'Li ñu bëgg',
    'confirm_unlock': 'Ubbi',
    'default_savings_name': 'Dénc',
    'savings_footer_info': 'Xaliss bi am na kaarange ci partenaire.',
    'join_request_subtitle': 'Dafa bëgg bokk ci natt bi',
    'confirm': 'Dëggal',
    'error_missing_fields': 'Fàww nga fessal yëpp',
    'error_accept_cgu': 'Nangul CGU yi',
    'invitation_sent_success': 'Invitation bi dem na ci @name !',
  };

  LocalizationState copyWith({AppLanguage? language}) {
    return LocalizationState(language: language ?? this.language);
  }
}

class LocalizationNotifier extends StateNotifier<LocalizationState> {
  LocalizationNotifier() : super(LocalizationState());

  void toggleLanguage() {
    state = state.copyWith(
      language: state.language == AppLanguage.fr ? AppLanguage.wo : AppLanguage.fr,
    );
  }

  void setLanguage(AppLanguage lang) {
    state = state.copyWith(language: lang);
  }
}

final localizationProvider = StateNotifierProvider<LocalizationNotifier, LocalizationState>((ref) {
  return LocalizationNotifier();
});
