import 'package:flutter_riverpod/flutter_riverpod.dart';

enum AppLanguage { fr, wo }

class LocalizationState {
  final AppLanguage language;

  LocalizationState({this.language = AppLanguage.fr});

  String translate(String key) {
    if (language == AppLanguage.fr) {
      return _fr[key] ?? key;
    } else {
      return _wo[key] ?? _fr[key] ?? key;
    }
  }

  static const Map<String, String> _fr = {
    'honor_score_title': 'Score d\'Honneur',
    'honor_score_status': 'Réputation : Standard',
    'honor_score_welcome': 'Bienvenue sur Tontetic ! Vous commencez avec un Score d’Honneur de 50. Votre assiduité déterminera votre accès aux futurs cercles et marchands Premium. Chaque paiement validé augmente votre score.',
    'coach_signature': 'Tontii (votre Coach Financier) :',
    'coach_bravo_msg': '« Bravo ! Votre assiduité ce mois-ci a maintenu votre score à 50. Continuez ainsi pour atteindre le niveau 60 et débloquer les tontines "Électroménager" ! »',
    'rules_title': 'Règles de Fiabilité ⚖️',
    'rules_content': 'Votre Score d\'Honneur (0-100) est le reflet de votre comportement sur la plateforme. \n\n📈 +5 points : Par cotisation payée à temps.\n⚠️ -20 points : Par retard de paiement.\n🚫 < 30 : Accès restreint aux cercles publiques.\n✨ > 80 : Accès aux Cercles Marchands Premium (Achat immédiat).',
    'coach_greeting': 'Bonjour ! Je suis Tontii (votre Coach Financier) 🧠.\nPosez-moi une question sur vos finances ou nos tontines ! Je suis là pour vous accompagner.',
    'tontii_typing': 'Tontii réfléchit...',
    'ask_question': 'Posez votre question...',
    'my_tontines': 'Mes Tontines',
    'explore': 'Explorer',
    'community': 'Communauté',
    'sim_target_amount': 'Montant cible',
    'sim_monthly_contribution': 'Mensualité',
    'sim_estimated_time': 'Temps estimé',
    'sim_solo_label': 'Économie Solo',
    'sim_tontine_label': 'Effet Tontine',
    'sim_coach_expl': 'Regardez cet avantage ! Seul, vous avancez à votre rythme, mais ensemble, vous accédez à vos rêves beaucoup plus vite.',
    'sim_legal_note': 'Ceci est une illustration technique. Les montants sont dépendants de la diligence des membres.',
    'dir_bi': 'Durée',
    'ki_jel': 'Bénéficiaire',
    'legal_primacy': 'En cas de divergence d\'interprétation, la version française des conditions générales fait foi.',
    'tab_home': 'Accueil',
    'tab_explore': 'Explorer',
    'tab_wallet': 'Portefeuille',
    'tab_merchant': 'Marchands',
    'search_placeholder': 'Chercher projet, membre...',
    'tab_circles': 'Cercles',
    'tab_community': 'Communauté',
    'filter_for_you': 'Pour vous',
    'filter_proximity': 'Proximité',
    'members_count': 'cercles',
    'followers_count': 'abonnés',
    'following': 'Suivi',
    'follow': 'Suivre',
    'request_sent': 'Demande envoyée !',
    'wallet_title': 'Synthèse PSP',
    'congrats': 'FÉLICITATIONS !',
    'pot_received': 'Vous avez reçu votre pot de ',
    'total_balance': 'Synthèse Opérations',
    'deposit': 'Crédit PSP',
    'wealth_analysis': 'Analyse de Patrimoine',
    'organic_growth': 'Croissance organique = Cotisations (0% Intérêts)',
    'project_safe': 'Blocage Volontaire',
    'lock_gains': 'Bloquer des fonds pour mon objectif',
    'zero_commission': '0% Commission Tontetic',
    'zero_commission_desc': 'Nous ne prélevons RIEN sur votre capital. Vos fonds sont chez le PSP agréé.',
    'transaction_history': 'Historique des opérations',
    'bank_disclaimer': 'Tontetic = outil technique. Vos fonds sont détenus par les PSP agréés (Wave/Stripe), pas par Tontetic.',
    'merchant_tab_title': '🛒 Découverte',
    'like': 'J\'aime',
    'share': 'Partager',
    'save': 'Cotiser',
    'start_saving': 'LANCER MA TONTINE 🚀',
    'hello': 'Bonjour',
    'welcome_back': 'Heureux de vous revoir !',
    'coach_ia': 'Coach IA',
    'sim_my_savings': 'SIMULATION DE TONTINE',
    'launch_offer': 'OFFRE LANCEMENT 🚀',
    'launch_offer_desc': 'Forfait STARTER Offert pendant 3 Mois !',
    'launch_offer_detail': 'Pour les 20 premiers créateurs de cercles Starter et leurs invités : 3 mois offerts.',
    'see_conditions': 'VOIR CONDITIONS & PROFITER',
    'social_proof': '142 personnes ont rejoint Tontetic aujourd\'hui 🚀',
    'profile_title': 'Mon Profil Public',
    'verify_identity': 'Demander ma Certification (Profil de Confiance)',
    'profession': 'Profession',
    'job_label': 'Métier',
    'company_label': 'Entreprise',
    'account_type': 'Type de Compte',
    'bio_label': 'Biographie',
    'speak_about_you': 'Parlez de vous...',
    'privacy_note': 'Votre photo et nom sont toujours publics. Vous contrôlez la visibilité de votre Bio et Métier.',
    'language_label': 'Langue',
    'french': 'Français',
    'wolof': 'Wolof',
    'no_bio': 'Aucune bio pour le moment.',
    'voice_consent_title': 'Autorisation Microphone 🎙️',
    'voice_consent_msg': 'Tontetic souhaite utiliser votre microphone pour transcrire vos messages vocaux. \n\n🔒 Vos audio sont traités uniquement pour la transcription et ne sont pas stockés.',
    'voice_consent_accept': 'AUTORISER & PARLER',
    'voice_consent_decline': 'PLUS TARD',
    'voice_listening': 'Je vous écoute...',
    'voice_understood': 'J\'ai bien reçu votre message vocal. Voici ce que j\'ai compris : ',
    'voice_error_short': 'Message trop court.',
    'voice_error_fail': 'Échec de la transcription.',
    'voice_privacy_note': 'Vos fichiers vocaux sont supprimés immédiatement après leur transcription.',
    'voice_fallback_msg': 'Pardon, je n’ai pas bien saisi votre message. Pourriez-vous répéter un peu plus clairement, ou taper votre demande si vous préférez ? Je suis là pour vous aider !',
    'voice_repeat': 'Répéter',
    'voice_write': 'Écrire',
    'voice_tip': 'Conseil : Essayez de vous rapprocher du micro ou d\'aller dans un endroit plus calme pour que je vous entende mieux ! 🤫',
  };

  static const Map<String, String> _wo = {
    'honor_score_title': 'Score d\'Honneur',
    'honor_score_status': 'Mbooloo : Mi ngi ci diggu',
    'honor_score_welcome': 'Dalal jàmm ci Tontetic ! Ngir ñu mën a am koolute ci suñu diggante, sa Score d’Honneur 50 la tàmbalee. Score bi day wone ni nga takku ci sa mbir : fexeel ba sa mbindu (cotisation) yi tegu ci yoon, loolu mën na baaxal sa score ba nga mën a am solo ak marchand yu am classe. Deet ! Lu sorsé (retard) ak sa mbindu day yàq sa réputation ak sa bët ci natt (tontine) yi di ñëw !',
    'coach_signature': 'Tontii (sa Coach Financier) :',
    'coach_bravo_msg': '« Baax na ! Sa assiduité weer wii tax na sa score méngook 50. Wéyal ni ngiy feyee sa mbindu ba nga jot ci niveau 60, loolu dina la may nga jot ci natt "Électroménager" ! »',
    'rules_title': 'Sartu Fiabilité ⚖️',
    'rules_content': 'Sa Score d’Honneur (0-100) moo lay won ni ngay nekke ci plateforme bi. \n\n📈 +5 points : Bo feyee sa mbindu ci waxtu wi.\n⚠️ -20 points : Bo gataxee (retard) ci fey bi.\n🚫 < 30 : Dootoo jot ci yeneen natt yi.\n✨ > 80 : Dinga jot ci Marchands Premium (Jënd léegi jot léegi).',
    'coach_greeting': 'Dalal jàmm ! Man la Tontii (sa Coach Financier) 🧠.\nLaaj ma loo bëgg xam ci sa xaalis walla ci sunu natt yi ! Ma ngi lay topp.',
    'tontii_typing': 'Tontii mi ngi xalaat...',
    'ask_question': 'Laaj ma sa laaj...',
    'my_tontines': 'Sama natt',
    'explore': 'Gëstu',
    'community': 'Mbooloo',
    'legal_wolof_title': 'Sartu Tontetic (Wolof)',
    'role_title': 'Lu Tontetic di def',
    'role_content': 'Tontetic ab jumtukaay la rekk ngir gérée seeni natt. Duñu banque, té duñu téye xaalis. Xaalis bi Stripe wala Wave ñoo koy téye ci seen plateforme yu am kaarange.',
    'honor_score_legal_title': 'Sa Score d’Honneur',
    'honor_score_legal_content': 'Sa Score d’Honneur ci sa feyu mbindu la depand. Boo feye te tegu ci yoon, sa score day yokku. Boo sorsé (retard), sa score day wàññiku.',
    'sim_target_amount': 'Li nga bëgg am',
    'sim_monthly_contribution': 'Li ngay mbindu weer wu ne',
    'sim_estimated_time': 'Dir bi',
    'sim_solo_label': 'Sama bopp',
    'sim_tontine_label': 'Àndandoo',
    'sim_coach_expl': '« Xoolal li ! Boo doon dénc sa xaalis sa bopp rekk (épargne solo), dinga ci tàmbalee lëf ba mu nekk dëgg, waaye mën na la jël ay weer yu bare. Ak Tontetic, yaa ngi bokk natt ak yeneen nit. Loolu day tax nga mën a am li nga bëgg ci weer wu jëkk wi walla wu ñaareel wi. Fi nga doon xaar ba weer wu mujj wi, fii mën nga gawante ba am sa kër, sa oto, walla sa matériel ! »',
    'sim_legal_note': 'Lii ab natt la, feyu mbindu yi ñoo koy dëggal.',
    'dir_bi': 'Dir bi',
    'ki_jel': 'Ki jël',
    'legal_primacy': 'Bu amee lën-lën ci ni ñuy déggé sart yi, version faransé bi mooy dëgg.',
    'tab_home': 'Accueil',
    'tab_explore': 'Gëstu',
    'tab_wallet': 'Xaalis',
    'tab_merchant': 'Jaaykat',
    'search_placeholder': 'Wut ab projet, nit...',
    'tab_circles': 'Natt yi',
    'tab_community': 'Mbooloo',
    'filter_for_you': 'Yaw rekk',
    'filter_proximity': 'Jege',
    'members_count': 'natt',
    'followers_count': 'abonnés',
    'following': 'Wéy',
    'follow': 'Topp',
    'request_sent': 'Yabal nañ ko !',
    'wallet_title': 'Synthèse PSP',
    'congrats': 'MASHALLAH !',
    'pot_received': 'Jot nga sa pot bu tollu ci ',
    'total_balance': 'Synthèse Opérations',
    'deposit': 'Crédit PSP',
    'wealth_analysis': 'Xool ni sa xaalis di yokkoo',
    'organic_growth': 'Yokkuté lool : Mbindu yi la (0% Intérêts)',
    'project_safe': 'Blocage Volontaire',
    'lock_gains': 'Téye sa xaalis ngir sa projet',
    'zero_commission': '0% Commission Tontetic',
    'zero_commission_desc': 'Duñu jël lu mat dërëm ci sa xaalis. Sa xaalis mi ngi ci PSP agréé.',
    'transaction_history': 'Jënd ak jaay yi passé',
    'bank_disclaimer': 'Tontetic = outil technique. Sa xaalis mi ngi nekk ci PSP agréé (Wave/Stripe), dula nekk ci Tontetic.',
    'merchant_tab_title': '🛒 Gëstu jaaykat',
    'like': 'Beugg',
    'share': 'Séddo',
    'save': 'Dénc',
    'start_saving': 'TÀMBALEE DÉNC LÉÉGI 🚀',
    'hello': 'Nanga def',
    'welcome_back': 'Beg nañu ci yaw !',
    'coach_ia': 'Tontii Coach',
    'sim_my_savings': 'NATT SIMULATEUR',
    'launch_offer': 'OFFRE LANCEMENT 🚀',
    'launch_offer_desc': '3 Weer yoo feyul dërëm ci Starter !',
    'launch_offer_detail': 'Ngir 20 créateurs yi jëkk ak séen invités : 3 weer offerts.',
    'see_conditions': 'XOOLAL SART YI & PROFITEEL',
    'social_proof': '142 nit bokk nañu ci Tontetic tay 🚀',
    'profile_title': 'Sama Profil',
    'verify_identity': 'Demande sa Certification (Koolute)',
    'profession': 'Liggeey',
    'job_label': 'Léégey',
    'company_label': 'Etablissement',
    'account_type': 'Type de Compte',
    'bio_label': 'Sama mbir',
    'speak_about_you': 'Waxal ci sa bopp...',
    'privacy_note': 'Sa photo ak sa tour ñépp mën nañ ko xool. Yaw yaay gérée sa bio ak sa liggeey.',
    'language_label': 'Lakku',
    'french': 'Faransé',
    'wolof': 'Wolof',
    'no_bio': 'Amagul benn mbir ci boppam.',
    'voice_consent_title': 'Nangu Micro bi 🎙️',
    'voice_consent_msg': 'Tontetic bëgg na jël sa micro ngir bind li ngay wax. \n\n🔒 Sa voice duñ ko téye, dañ koy bind rekk.',
    'voice_consent_accept': 'NANGU NA & WAX',
    'voice_consent_decline': 'BENEEN YOON',
    'voice_listening': 'Ma ngi lay déglu...',
    'voice_understood': 'Jot nañu sa message vocal. Lii lañu ci dégg : ',
    'voice_error_short': 'Message bi gatt na.',
    'voice_error_fail': 'Bind bi sottiwul.',
    'voice_privacy_note': 'Sa voice duñ ko téye, dañ koy bind ba paré fat ko léégi.',
    'voice_fallback_msg': 'Baal ma, dégguma li nga wax bu baax. Mën nga ko waxaat lu leer walla nga mbind ko ci sa téléfon ? Ma ngi lay jàppale !',
    'voice_repeat': 'Waxaat',
    'voice_write': 'Mbind',
    'voice_tip': 'Conseil : Jegeel micro bi walla nga dem fula neex ba ma mën la dégg bu baax ! 🤫',
  };

  LocalizationState copyWith({AppLanguage? language}) {
    return LocalizationState(language: language ?? this.language);
  }
}

class LocalizationNotifier extends StateNotifier<LocalizationState> {
  LocalizationNotifier() : super(LocalizationState());

  void toggleLanguage() {
    state = state.copyWith(
      language: state.language == AppLanguage.fr ? AppLanguage.wo : AppLanguage.fr,
    );
  }

  void setLanguage(AppLanguage lang) {
    state = state.copyWith(language: lang);
  }
}

final localizationProvider = StateNotifierProvider<LocalizationNotifier, LocalizationState>((ref) {
  return LocalizationNotifier();
});
